### ISSUE TITLE
Research how to incorporate (BPMN) simulation with scenario creation

### ISSUE THREAD

**Issue by yT0n1** [BPChain/meta#104]
- [x] Investigate Scylla
- [x] short writing 200 words

**Comment by bisbaldi** [comment]
One common use case of combining BPMN diagrams with a blockchain-based technology is to log the current state of process instances on the blockchain. This is a useful way to prove the execution of specific tasks, their order and timestamps. 
To provide simulation scenarios, we want to make use of the already existing solution Scylla. A BPMN diagram with specified configurations will be provided to Scylla. The simulation will then run and Scylla will provide a XML file with the simulation traces. Each occurring event is logged and enriched with a timestamp and potentially also the resources needed. 
The output XML could be used to control the scenarios executed on BPChain. 
Only the timestamps are necessary to mock a scenario execution with our meta assets. More advanced solutions could also provide logging of the concrete task ids. 
To take advantage of the different nodes our implementation provides we currently have two different possible solutions:
1. Each node is connected to a resource specified in the configuration given to Scylla (number of nodes = number of resources). A node logs the events it is needed for. This might lead to problems with events that need more than one resource and those no one is responsible for. The master node could be used to log events without an associated resource.
2. Each node is associated to a single process instance. This will lead to an amount of nodes that equals the process instances. Each node than logs all the events that belong to the corresponding process instance. Problems might occur here due to the large amount of process instances.
