### ISSUE TITLE
Simulate/Precomputed execution of smart contracts

### ISSUE THREAD

**Issue by fyndalf** [BPChain/meta#69]
As a service provider I maybe want to have precomputed scenarios which can be replayed so non-priveleged (normal) users can "run" them.
- [x] 200 words summary of how this could be done
- [x] including short discussion of how some "configuration" could be part of this.

**Comment by bisbaldi** [comment]
As a non-privileged user one should not be able to start scenarios on the provided backend. In order to still achieve meaningful results, one should be able to replay precomputed scenario executions. 
In order to achieve this we have to execute the scenario a priori. The benchmarking results should be stored every 30 seconds in a database. In addition it would be useful to store timestamps, a scenario name and the given configurations (transaction interval, payload size).
When a non-privileged user wants to access such a scenario, he should be given a short description of what the scenario is representing. If the scenario has been precomputed with different configurations, a dropdown menu should provide the possible options to the user. When the user has decided on a scenario and configuration to run, the precomputed data is fetched from the database and displayed with the time delays they were stored in. To the user it looks like real time data then.

**Comment by t-lichtenstein** [comment]
The dataset has to be continuous with the same configuration and smart contract running during the whole time span. A time span should be at least 30 min long. No other chain should be running on the system at the time of the recording to prevent side effects. If all conditions are fulfilled, the data set can be stored in the mongodb in a 'precomputed' storage.
